name: my_sites
#these are your optional local services you can run 
include: 
    - ./_dev/environment/preprocessors/fpm/docker-compose.yml
    - ./_dev/environment/servers/nginx/docker-compose.yml
    - ./_dev/environment/servers/apache/docker-compose.yml
    - ./_dev/environment/databases/mariadb/docker-compose.yml
    #- ./_dev/environment/databases/mysql/docker-compose.yml
networks:
    my-sites-ide: