#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Dotenv\Dotenv;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Yiendos\MySitesIde\AssetsCommand;
use Yiendos\MySitesIde\DouseCommand;
use Yiendos\MySitesIde\SparkCommand;
use Yiendos\MySitesIde\BuildCommand AS ImageBuildCommand;
use Yiendos\MySitesIde\ComposerCommand;
use Yiendos\MySitesIde\CreateSiteCommand;
use Yiendos\MySitesIde\RepoCloneCommand;
use Yiendos\MySitesIde\RestartCommand;
use Yiendos\MySitesIde\PluginDiscoverCommand;
use Yiendos\MySitesIde\PluginEnvCommand;
use Yiendos\MySitesIde\PluginListCommand;
use Yiendos\MySitesIde\PluginSearchCommand;
use Yiendos\MySitesIde\Plugins\Discover;

$dotenv = Dotenv::createUnsafeImmutable(__DIR__);
$dotenv->load();

// the contract plugins use to find the project root (also in _dev/cache/ide.env for compose)
putenv('IDE_ROOT=' . __DIR__);

$application = new Application();

#ide
$application->add(new SparkCommand());
$application->add(new DouseCommand());
$application->add(new ImageBuildCommand());
$application->add(new RestartCommand());
$application->add(new CreateSiteCommand());
$application->add(new RepoCloneCommand());
$application->add(new ComposerCommand());
$application->add(new AssetsCommand());
$application->add(new PluginListCommand());
$application->add(new PluginDiscoverCommand());
$application->add(new PluginEnvCommand());
$application->add(new PluginSearchCommand());

#plugins - every installed Composer package of type my-sites-ide-plugin
foreach (Discover::load() as $plugin)
{
    // after the root .env, and immutable, so the user's root values always win
    if ($plugin['env'] !== null)
    {
        Dotenv::createUnsafeImmutable(__DIR__ . '/' . dirname($plugin['env']), basename($plugin['env']))->safeLoad();
    }

    foreach ($plugin['commands'] as $class)
    {
        if (is_subclass_of($class, Command::class) && !(new ReflectionClass($class))->isAbstract())
        {
            $application->add(new $class());
        }
    }
}

/** If the user has a deployment mechanism installed via composer */
if (class_exists('Yiendos\Deploy\Console\Commands')) 
{
    $commands = (new \Yiendos\Deploy\Console\Commands)->getList();

    foreach($commands as $command)
    {
        $object = new ReflectionClass($command);
        $obj = $object->newInstanceArgs([]);
        $application->add($obj);
    }
}

$application->run();