#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Yiendos\Deploy\Console\InputOutputCommand;

$command = new InputOutputCommand();

$application = new Application();

$application->add($command);

$application->run();