version: '2'
x-project: ~project~
x-path: ~pwd~
services:
    apache:
        build:
            context: .
            dockerfile: _mysites/docker/apache2/Dockerfile
        container_name: ~project~_apache
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            - FPM_SOCK=~project~_php_fpm
        volumes:
            - ./_mysites/docker/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./_mysites/docker/apache2/sites-enabled:/usr/local/apache2/sites-enabled
            - ./_mysites/docker/logs/apache2/:/var/log/apache2
            - 'code-mount:/Sites'
            - 'projects-mount:/Projects'
        command: ["/usr/local/apache2/bin/apachectl", "-D",  "FOREGROUND"]
    nginx:
        build:
            context: .
            dockerfile: _mysites/docker/nginx/Dockerfile
        container_name: ~project~_nginx
        ports:
            - "8081:8081"
        environment:
            - NGINX_PORT=8081
            - FPM_SOCK=~project~_php_fpm
        volumes:
            - 'code-mount:/Sites'
            - 'projects-mount:/Projects'
            - ./_mysites/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./_mysites/docker/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./_mysites/docker/logs/nginx:/var/log/nginx/
    php_fpm:
        build:
            context: .
            dockerfile: _mysites/docker/php/Dockerfile
        container_name: ~project~_php_fpm
        volumes:
            -  'code-mount:/Sites'
            -  'projects-mount:/Projects'
            -  ./_mysites/docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    db:
        image: mysql:5.7
        container_name: ~project~_mysql
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=0
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=sites_default
            - MYSQL_USER=joomlatools
            - MYSQL_PASSWORD=joomlatools
            - MYSQL_ROOT_PASSWORD=root
        command: ["mysqld", "--sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]
        volumes:
            - ./_mysites/docker/mysql/:/docker-entrypoint-initdb.d/
            - ./_mysites/docker/mysql/conf/my.cnf:/etc/mysql/mysql.cnf
    theia:
        image: theiaide/theia-php:latest
        container_name: ~project~_theias
        logging:
            driver: "none"
        ports:
            - "3000:3000"
        volumes:
            - 'code-mount:/home/project/Sites'
            - 'projects-mount:/home/project/Projects'
            - ./_mysites/docker/theia/.theia/settings.json:/home/theia/.theia/settings.json
            - ./_mysites/docker/theia/.gitconfig:/home/theia/.gitconfig
    mailhog:
        container_name: ~project~_mailhog
        image: mailhog/mailhog
        ports:
            - "8083:8025"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - "db"
        container_name: ~project~_phpmyadmin
        environment:
            - PMA_HOST=db
        restart: always
        ports:
            - "8084:80"
volumes:
    code-mount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PWD}/Sites"
    projects-mount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PWD}/Projects"