version: '2'
x-project: ~project~
x-path: ~pwd~
services:
    apache:
        image: mysites_apache2:latest
        #build:
        #    context: .
        #    dockerfile: _mysites/docker/apache2/Dockerfile
        container_name: ~project~_apache
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            - FPM_SOCK=~project~_php_fpm
        volumes:
            - ./_mysites/docker/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./_mysites/docker/apache2/sites-enabled:/usr/local/apache2/sites-enabled
            - ./_mysites/docker/logs/apache2/:/var/log/apache2
            - ./Sites:/Sites
            - ./Projects:/Projects
        command: ["/usr/local/apache2/bin/apachectl", "-D",  "FOREGROUND"]
    nginx:
        image: mysites_nginx:latest
        #build:
        #    context: .
        #    dockerfile: _mysites/docker/nginx/Dockerfile
        container_name: ~project~_nginx
        ports:
            - "8081:8081"
        environment:
            - NGINX_PORT=8081
            - FPM_SOCK=~project~_php_fpm
        volumes:
            - ./Sites:/Sites
            - ./Projects:/Projects
            - ./_mysites/docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
            - ./_mysites/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./_mysites/docker/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./_mysites/docker/logs/nginx:/var/log/nginx/
    php_fpm:
        image: mysites_php:latest
        #build:
        #    context: .
        #    dockerfile: _mysites/docker/php/Dockerfile
        container_name: ~project~_php_fpm
        volumes:
            - ./Sites:/Sites
            - ./Projects:/Projects
            -  ./_mysites/docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    db:
        image: mysql/mysql-server:8.0.23-1.1.19
        container_name: ~project~_mysql
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=0
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=sites_default
            - MYSQL_USER=joomlatools
            - MYSQL_PASSWORD=joomlatools
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./_mysites/docker/mysql/:/docker-entrypoint-initdb.d/
            - ./_mysites/docker/mysql/conf/my-arm.cnf:/etc/mysql/mysql.cnf
    theia:
        image: theiaide/theia-php:latest
        container_name: ~project~_theias
        logging:
            driver: "none"
        ports:
            - "3000:3000"
        volumes:
            - ./Sites:/home/project/Sites
            - ./Projects:/home/project/Projects
            - ./_mysites/docker/theia/.theia/settings.json:/home/theia/.theia/settings.json
            - ./_mysites/docker/theia/.gitconfig:/home/theia/.gitconfig
    mailhog:
        container_name: ~project~_mailhog
        image: mailhog/mailhog
        ports:
            - "8083:8025"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - "db"
        container_name: ~project~_phpmyadmin
        environment:
            - PMA_HOST=db
        restart: always
        ports:
            - "8084:80"