name: build
on:
  push

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: create fake .env 
        run: touch .env
      - name: Build images
        run: docker compose up -d ${{ secrets.APP }} --build
        env: 
            NAMESPACE: ${{ secrets.NAMESPACE }}
            APP: ${{ secrets.APP }}
      - name: Run trivy over cron 
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'my_site_cron'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Run trivy over nginx 
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'my_site_nginx'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Run trivy over fpm 
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'my_site_fpm'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Run trivy over apache 
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'my_site_apache'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'